package:
  name: hello
  version: 0
  epoch: 0
  description: "a hello world program"
  copyright:
    - paths:
      - "*"
      attestation: |
        This program is in the public domain.
      license: CC-PDDC
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
    packages:
      - alpine-baselayout-data
      - busybox
      - build-base
      - scanelf
      - ssl_client
      - ca-certificates-bundle

pipeline:
  - name: Build Static
    runs: |
      gcc -static -o hello hello.c

  - name: Install
    runs: |
      mkdir -p "${{targets.destdir}}/usr/bin"
      install -Dm755 hello "${{targets.destdir}}/usr/bin/hello"

  - uses: strip